{
 "title": "日志分析",
 "tags": [
  "logs",
  "analysis"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "time_range",
    "label": "时间范围",
    "query": "最新1小时 : 1h, 最新6小时 : 6h, 最新24小时 : 24h, 最新7天 : 7d"
   },
   { "name": "search_keyword", "label": "搜索关键词" }
  ]
 },
 "panels": [
  {
   "title": "错误日志",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"injective-node\"} |~ \"(ERR|FATAL|PANIC)\" [${time_range}])) or vector(0)"
    }
   ]
  },
  {
   "title": "警告日志",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"injective-node\"} |~ \"WRN\" [${time_range}])) or vector(0)"
    }
   ]
  },
  {
   "title": "信息日志",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"injective-node\"} |~ \"INF\" [${time_range}])) or vector(0)"
    }
   ]
  },
  {
   "title": "总日志数",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"injective-node\"}[${time_range}])) or vector(0)"
    }
   ]
  },
  {
   "title": "关键错误日志",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "{job=\"injective-node\"} |~ \"(ERR|FATAL|PANIC)\" |= \"$search_keyword\""
    }
   ]
  }
 ]
}